//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSILab.Jupiter.Webservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Classe", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Classe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Annee_Promo_SortanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_ClasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Encore_PresenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Annee_Promo_Sortante {
            get {
                return this.Annee_Promo_SortanteField;
            }
            set {
                if ((this.Annee_Promo_SortanteField.Equals(value) != true)) {
                    this.Annee_Promo_SortanteField = value;
                    this.RaisePropertyChanged("Annee_Promo_Sortante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Classe {
            get {
                return this.Code_ClasseField;
            }
            set {
                if ((this.Code_ClasseField.Equals(value) != true)) {
                    this.Code_ClasseField = value;
                    this.RaisePropertyChanged("Code_Classe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Encore_Presente {
            get {
                return this.Encore_PresenteField;
            }
            set {
                if ((this.Encore_PresenteField.Equals(value) != true)) {
                    this.Encore_PresenteField = value;
                    this.RaisePropertyChanged("Encore_Presente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Libelle {
            get {
                return this.LibelleField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleField, value) != true)) {
                    this.LibelleField = value;
                    this.RaisePropertyChanged("Libelle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Conference", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Conference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_ConferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_Heure_DebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_Heure_FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublieeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPSILab.Jupiter.Webservice.Ville VilleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Conference {
            get {
                return this.Code_ConferenceField;
            }
            set {
                if ((this.Code_ConferenceField.Equals(value) != true)) {
                    this.Code_ConferenceField = value;
                    this.RaisePropertyChanged("Code_Conference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Heure_Debut {
            get {
                return this.Date_Heure_DebutField;
            }
            set {
                if ((this.Date_Heure_DebutField.Equals(value) != true)) {
                    this.Date_Heure_DebutField = value;
                    this.RaisePropertyChanged("Date_Heure_Debut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Heure_Fin {
            get {
                return this.Date_Heure_FinField;
            }
            set {
                if ((this.Date_Heure_FinField.Equals(value) != true)) {
                    this.Date_Heure_FinField = value;
                    this.RaisePropertyChanged("Date_Heure_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lieu {
            get {
                return this.LieuField;
            }
            set {
                if ((object.ReferenceEquals(this.LieuField, value) != true)) {
                    this.LieuField = value;
                    this.RaisePropertyChanged("Lieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Publiee {
            get {
                return this.PublieeField;
            }
            set {
                if ((this.PublieeField.Equals(value) != true)) {
                    this.PublieeField = value;
                    this.RaisePropertyChanged("Publiee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EPSILab.Jupiter.Webservice.Ville Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ville", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Ville : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_VilleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Ville {
            get {
                return this.Code_VilleField;
            }
            set {
                if ((this.Code_VilleField.Equals(value) != true)) {
                    this.Code_VilleField = value;
                    this.RaisePropertyChanged("Code_Ville");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Libelle {
            get {
                return this.LibelleField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleField, value) != true)) {
                    this.LibelleField = value;
                    this.RaisePropertyChanged("Libelle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortOrder", Namespace="http://schemas.datacontract.org/2004/07/System.Data.SqlClient")]
    public enum SortOrder : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ascending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Descending = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lien", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Lien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_LienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Lien {
            get {
                return this.Code_LienField;
            }
            set {
                if ((this.Code_LienField.Equals(value) != true)) {
                    this.Code_LienField = value;
                    this.RaisePropertyChanged("Code_Lien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ordre {
            get {
                return this.OrdreField;
            }
            set {
                if ((this.OrdreField.Equals(value) != true)) {
                    this.OrdreField = value;
                    this.RaisePropertyChanged("Ordre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Membre", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Membre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPSILab.Jupiter.Webservice.Classe ClasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_MembreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_EPSIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_persoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mot_de_passeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PresentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PseudoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPSILab.Jupiter.Webservice.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Site_webField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telephone_mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_FacebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_LinkedInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_TwitterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_ViadeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPSILab.Jupiter.Webservice.Ville VilleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ville_origineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EPSILab.Jupiter.Webservice.Classe Classe {
            get {
                return this.ClasseField;
            }
            set {
                if ((object.ReferenceEquals(this.ClasseField, value) != true)) {
                    this.ClasseField = value;
                    this.RaisePropertyChanged("Classe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Membre {
            get {
                return this.Code_MembreField;
            }
            set {
                if ((this.Code_MembreField.Equals(value) != true)) {
                    this.Code_MembreField = value;
                    this.RaisePropertyChanged("Code_Membre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_EPSI {
            get {
                return this.Email_EPSIField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_EPSIField, value) != true)) {
                    this.Email_EPSIField = value;
                    this.RaisePropertyChanged("Email_EPSI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_perso {
            get {
                return this.Email_persoField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_persoField, value) != true)) {
                    this.Email_persoField = value;
                    this.RaisePropertyChanged("Email_perso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mot_de_passe {
            get {
                return this.Mot_de_passeField;
            }
            set {
                if ((object.ReferenceEquals(this.Mot_de_passeField, value) != true)) {
                    this.Mot_de_passeField = value;
                    this.RaisePropertyChanged("Mot_de_passe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivations {
            get {
                return this.MotivationsField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivationsField, value) != true)) {
                    this.MotivationsField = value;
                    this.RaisePropertyChanged("Motivations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Presentation {
            get {
                return this.PresentationField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentationField, value) != true)) {
                    this.PresentationField = value;
                    this.RaisePropertyChanged("Presentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pseudo {
            get {
                return this.PseudoField;
            }
            set {
                if ((object.ReferenceEquals(this.PseudoField, value) != true)) {
                    this.PseudoField = value;
                    this.RaisePropertyChanged("Pseudo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EPSILab.Jupiter.Webservice.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Site_web {
            get {
                return this.Site_webField;
            }
            set {
                if ((object.ReferenceEquals(this.Site_webField, value) != true)) {
                    this.Site_webField = value;
                    this.RaisePropertyChanged("Site_web");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((object.ReferenceEquals(this.StatutField, value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone_mobile {
            get {
                return this.Telephone_mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.Telephone_mobileField, value) != true)) {
                    this.Telephone_mobileField = value;
                    this.RaisePropertyChanged("Telephone_mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_Facebook {
            get {
                return this.URL_FacebookField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_FacebookField, value) != true)) {
                    this.URL_FacebookField = value;
                    this.RaisePropertyChanged("URL_Facebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_LinkedIn {
            get {
                return this.URL_LinkedInField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_LinkedInField, value) != true)) {
                    this.URL_LinkedInField = value;
                    this.RaisePropertyChanged("URL_LinkedIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_Twitter {
            get {
                return this.URL_TwitterField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_TwitterField, value) != true)) {
                    this.URL_TwitterField = value;
                    this.RaisePropertyChanged("URL_Twitter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_Viadeo {
            get {
                return this.URL_ViadeoField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_ViadeoField, value) != true)) {
                    this.URL_ViadeoField = value;
                    this.RaisePropertyChanged("URL_Viadeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EPSILab.Jupiter.Webservice.Ville Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ville_origine {
            get {
                return this.Ville_origineField;
            }
            set {
                if ((object.ReferenceEquals(this.Ville_origineField, value) != true)) {
                    this.Ville_origineField = value;
                    this.RaisePropertyChanged("Ville_origine");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Role {
            get {
                return this.Code_RoleField;
            }
            set {
                if ((this.Code_RoleField.Equals(value) != true)) {
                    this.Code_RoleField = value;
                    this.RaisePropertyChanged("Code_Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Libelle {
            get {
                return this.LibelleField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleField, value) != true)) {
                    this.LibelleField = value;
                    this.RaisePropertyChanged("Libelle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="News", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class News : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_NewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_HeureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPSILab.Jupiter.Webservice.Membre MembreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mots_ClesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublieeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texte_CourtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texte_LongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_News {
            get {
                return this.Code_NewsField;
            }
            set {
                if ((this.Code_NewsField.Equals(value) != true)) {
                    this.Code_NewsField = value;
                    this.RaisePropertyChanged("Code_News");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Heure {
            get {
                return this.Date_HeureField;
            }
            set {
                if ((this.Date_HeureField.Equals(value) != true)) {
                    this.Date_HeureField = value;
                    this.RaisePropertyChanged("Date_Heure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EPSILab.Jupiter.Webservice.Membre Membre {
            get {
                return this.MembreField;
            }
            set {
                if ((object.ReferenceEquals(this.MembreField, value) != true)) {
                    this.MembreField = value;
                    this.RaisePropertyChanged("Membre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mots_Cles {
            get {
                return this.Mots_ClesField;
            }
            set {
                if ((object.ReferenceEquals(this.Mots_ClesField, value) != true)) {
                    this.Mots_ClesField = value;
                    this.RaisePropertyChanged("Mots_Cles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Publiee {
            get {
                return this.PublieeField;
            }
            set {
                if ((this.PublieeField.Equals(value) != true)) {
                    this.PublieeField = value;
                    this.RaisePropertyChanged("Publiee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texte_Court {
            get {
                return this.Texte_CourtField;
            }
            set {
                if ((object.ReferenceEquals(this.Texte_CourtField, value) != true)) {
                    this.Texte_CourtField = value;
                    this.RaisePropertyChanged("Texte_Court");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texte_Long {
            get {
                return this.Texte_LongField;
            }
            set {
                if ((object.ReferenceEquals(this.Texte_LongField, value) != true)) {
                    this.Texte_LongField = value;
                    this.RaisePropertyChanged("Texte_Long");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Projet", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Projet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvancementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_ProjetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPSILab.Jupiter.Webservice.Ville VilleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Avancement {
            get {
                return this.AvancementField;
            }
            set {
                if ((this.AvancementField.Equals(value) != true)) {
                    this.AvancementField = value;
                    this.RaisePropertyChanged("Avancement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Projet {
            get {
                return this.Code_ProjetField;
            }
            set {
                if ((this.Code_ProjetField.Equals(value) != true)) {
                    this.Code_ProjetField = value;
                    this.RaisePropertyChanged("Code_Projet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EPSILab.Jupiter.Webservice.Ville Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Publicite", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Publicite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_PubliciteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PresentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublieeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Publicite {
            get {
                return this.Code_PubliciteField;
            }
            set {
                if ((this.Code_PubliciteField.Equals(value) != true)) {
                    this.Code_PubliciteField = value;
                    this.RaisePropertyChanged("Code_Publicite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Presentation {
            get {
                return this.PresentationField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentationField, value) != true)) {
                    this.PresentationField = value;
                    this.RaisePropertyChanged("Presentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Publiee {
            get {
                return this.PublieeField;
            }
            set {
                if ((this.PublieeField.Equals(value) != true)) {
                    this.PublieeField = value;
                    this.RaisePropertyChanged("Publiee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salon", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Salon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_SalonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_Heure_DebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_Heure_FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Salon {
            get {
                return this.Code_SalonField;
            }
            set {
                if ((this.Code_SalonField.Equals(value) != true)) {
                    this.Code_SalonField = value;
                    this.RaisePropertyChanged("Code_Salon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Heure_Debut {
            get {
                return this.Date_Heure_DebutField;
            }
            set {
                if ((this.Date_Heure_DebutField.Equals(value) != true)) {
                    this.Date_Heure_DebutField = value;
                    this.RaisePropertyChanged("Date_Heure_Debut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Heure_Fin {
            get {
                return this.Date_Heure_FinField;
            }
            set {
                if ((this.Date_Heure_FinField.Equals(value) != true)) {
                    this.Date_Heure_FinField = value;
                    this.RaisePropertyChanged("Date_Heure_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lieu {
            get {
                return this.LieuField;
            }
            set {
                if ((object.ReferenceEquals(this.LieuField, value) != true)) {
                    this.LieuField = value;
                    this.RaisePropertyChanged("Lieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Publie {
            get {
                return this.PublieField;
            }
            set {
                if ((this.PublieField.Equals(value) != true)) {
                    this.PublieField = value;
                    this.RaisePropertyChanged("Publie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservice.IClasseReader")]
    public interface IClasseReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasseReader/GetClasse", ReplyAction="http://tempuri.org/IClasseReader/GetClasseResponse")]
        EPSILab.Jupiter.Webservice.Classe GetClasse(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasseReader/GetClasses", ReplyAction="http://tempuri.org/IClasseReader/GetClassesResponse")]
        EPSILab.Jupiter.Webservice.Classe[] GetClasses();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClasseReaderChannel : EPSILab.Jupiter.Webservice.IClasseReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClasseReaderClient : System.ServiceModel.ClientBase<EPSILab.Jupiter.Webservice.IClasseReader>, EPSILab.Jupiter.Webservice.IClasseReader {
        
        public ClasseReaderClient() {
        }
        
        public ClasseReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClasseReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClasseReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClasseReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.Jupiter.Webservice.Classe GetClasse(int code) {
            return base.Channel.GetClasse(code);
        }
        
        public EPSILab.Jupiter.Webservice.Classe[] GetClasses() {
            return base.Channel.GetClasses();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservice.IConferenceReader")]
    public interface IConferenceReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/GetConference", ReplyAction="http://tempuri.org/IConferenceReader/GetConferenceResponse")]
        EPSILab.Jupiter.Webservice.Conference GetConference(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/GetConferences", ReplyAction="http://tempuri.org/IConferenceReader/GetConferencesResponse")]
        EPSILab.Jupiter.Webservice.Conference[] GetConferences();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/GetConferencesLimited", ReplyAction="http://tempuri.org/IConferenceReader/GetConferencesLimitedResponse")]
        EPSILab.Jupiter.Webservice.Conference[] GetConferencesLimited(int indexFirstResult, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/GetConferencesSorted", ReplyAction="http://tempuri.org/IConferenceReader/GetConferencesSortedResponse")]
        EPSILab.Jupiter.Webservice.Conference[] GetConferencesSorted(int indexFirstResult, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/GetConferencesByVille", ReplyAction="http://tempuri.org/IConferenceReader/GetConferencesByVilleResponse")]
        EPSILab.Jupiter.Webservice.Conference[] GetConferencesByVille(EPSILab.Jupiter.Webservice.Ville ville, int indexFirstResult, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/GetConferenceLastInsertedId", ReplyAction="http://tempuri.org/IConferenceReader/GetConferenceLastInsertedIdResponse")]
        int GetConferenceLastInsertedId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/SearchConferences", ReplyAction="http://tempuri.org/IConferenceReader/SearchConferencesResponse")]
        EPSILab.Jupiter.Webservice.Conference[] SearchConferences(string keywords);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConferenceReaderChannel : EPSILab.Jupiter.Webservice.IConferenceReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConferenceReaderClient : System.ServiceModel.ClientBase<EPSILab.Jupiter.Webservice.IConferenceReader>, EPSILab.Jupiter.Webservice.IConferenceReader {
        
        public ConferenceReaderClient() {
        }
        
        public ConferenceReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConferenceReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.Jupiter.Webservice.Conference GetConference(int code) {
            return base.Channel.GetConference(code);
        }
        
        public EPSILab.Jupiter.Webservice.Conference[] GetConferences() {
            return base.Channel.GetConferences();
        }
        
        public EPSILab.Jupiter.Webservice.Conference[] GetConferencesLimited(int indexFirstResult, int numberOfResults) {
            return base.Channel.GetConferencesLimited(indexFirstResult, numberOfResults);
        }
        
        public EPSILab.Jupiter.Webservice.Conference[] GetConferencesSorted(int indexFirstResult, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order) {
            return base.Channel.GetConferencesSorted(indexFirstResult, numberOfResults, order);
        }
        
        public EPSILab.Jupiter.Webservice.Conference[] GetConferencesByVille(EPSILab.Jupiter.Webservice.Ville ville, int indexFirstResult, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order) {
            return base.Channel.GetConferencesByVille(ville, indexFirstResult, numberOfResults, order);
        }
        
        public int GetConferenceLastInsertedId() {
            return base.Channel.GetConferenceLastInsertedId();
        }
        
        public EPSILab.Jupiter.Webservice.Conference[] SearchConferences(string keywords) {
            return base.Channel.SearchConferences(keywords);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservice.ILienReader")]
    public interface ILienReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILienReader/GetLien", ReplyAction="http://tempuri.org/ILienReader/GetLienResponse")]
        EPSILab.Jupiter.Webservice.Lien GetLien(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILienReader/GetLiens", ReplyAction="http://tempuri.org/ILienReader/GetLiensResponse")]
        EPSILab.Jupiter.Webservice.Lien[] GetLiens();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILienReaderChannel : EPSILab.Jupiter.Webservice.ILienReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LienReaderClient : System.ServiceModel.ClientBase<EPSILab.Jupiter.Webservice.ILienReader>, EPSILab.Jupiter.Webservice.ILienReader {
        
        public LienReaderClient() {
        }
        
        public LienReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LienReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LienReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LienReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.Jupiter.Webservice.Lien GetLien(int code) {
            return base.Channel.GetLien(code);
        }
        
        public EPSILab.Jupiter.Webservice.Lien[] GetLiens() {
            return base.Channel.GetLiens();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservice.IMembreReader")]
    public interface IMembreReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreReader/GetMembre", ReplyAction="http://tempuri.org/IMembreReader/GetMembreResponse")]
        EPSILab.Jupiter.Webservice.Membre GetMembre(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreReader/GetMembres", ReplyAction="http://tempuri.org/IMembreReader/GetMembresResponse")]
        EPSILab.Jupiter.Webservice.Membre[] GetMembres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreReader/GetMembresLimited", ReplyAction="http://tempuri.org/IMembreReader/GetMembresLimitedResponse")]
        EPSILab.Jupiter.Webservice.Membre[] GetMembresLimited(int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreReader/GetMembresSorted", ReplyAction="http://tempuri.org/IMembreReader/GetMembresSortedResponse")]
        EPSILab.Jupiter.Webservice.Membre[] GetMembresSorted(int indexFirstElement, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreReader/GetMembresByVilleAndRole", ReplyAction="http://tempuri.org/IMembreReader/GetMembresByVilleAndRoleResponse")]
        EPSILab.Jupiter.Webservice.Membre[] GetMembresByVilleAndRole(EPSILab.Jupiter.Webservice.Ville ville, EPSILab.Jupiter.Webservice.Role role, int indexFirstResult, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreReader/GetMembreLastInsertedId", ReplyAction="http://tempuri.org/IMembreReader/GetMembreLastInsertedIdResponse")]
        int GetMembreLastInsertedId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreReader/SearchMembres", ReplyAction="http://tempuri.org/IMembreReader/SearchMembresResponse")]
        EPSILab.Jupiter.Webservice.Membre[] SearchMembres(string keywords);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMembreReaderChannel : EPSILab.Jupiter.Webservice.IMembreReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MembreReaderClient : System.ServiceModel.ClientBase<EPSILab.Jupiter.Webservice.IMembreReader>, EPSILab.Jupiter.Webservice.IMembreReader {
        
        public MembreReaderClient() {
        }
        
        public MembreReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MembreReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MembreReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MembreReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.Jupiter.Webservice.Membre GetMembre(int code) {
            return base.Channel.GetMembre(code);
        }
        
        public EPSILab.Jupiter.Webservice.Membre[] GetMembres() {
            return base.Channel.GetMembres();
        }
        
        public EPSILab.Jupiter.Webservice.Membre[] GetMembresLimited(int indexFirstElement, int numberOfResults) {
            return base.Channel.GetMembresLimited(indexFirstElement, numberOfResults);
        }
        
        public EPSILab.Jupiter.Webservice.Membre[] GetMembresSorted(int indexFirstElement, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order) {
            return base.Channel.GetMembresSorted(indexFirstElement, numberOfResults, order);
        }
        
        public EPSILab.Jupiter.Webservice.Membre[] GetMembresByVilleAndRole(EPSILab.Jupiter.Webservice.Ville ville, EPSILab.Jupiter.Webservice.Role role, int indexFirstResult, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order) {
            return base.Channel.GetMembresByVilleAndRole(ville, role, indexFirstResult, numberOfResults, order);
        }
        
        public int GetMembreLastInsertedId() {
            return base.Channel.GetMembreLastInsertedId();
        }
        
        public EPSILab.Jupiter.Webservice.Membre[] SearchMembres(string keywords) {
            return base.Channel.SearchMembres(keywords);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservice.INewsReader")]
    public interface INewsReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsReader/GetNews", ReplyAction="http://tempuri.org/INewsReader/GetNewsResponse")]
        EPSILab.Jupiter.Webservice.News GetNews(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsReader/GetListNews", ReplyAction="http://tempuri.org/INewsReader/GetListNewsResponse")]
        EPSILab.Jupiter.Webservice.News[] GetListNews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsReader/GetListNewsLimited", ReplyAction="http://tempuri.org/INewsReader/GetListNewsLimitedResponse")]
        EPSILab.Jupiter.Webservice.News[] GetListNewsLimited(int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsReader/GetListNewsSorted", ReplyAction="http://tempuri.org/INewsReader/GetListNewsSortedResponse")]
        EPSILab.Jupiter.Webservice.News[] GetListNewsSorted(int indexFirstElement, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsReader/GetNewsLastInsertedId", ReplyAction="http://tempuri.org/INewsReader/GetNewsLastInsertedIdResponse")]
        int GetNewsLastInsertedId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsReader/SearchNews", ReplyAction="http://tempuri.org/INewsReader/SearchNewsResponse")]
        EPSILab.Jupiter.Webservice.News[] SearchNews(string keywords);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsReaderChannel : EPSILab.Jupiter.Webservice.INewsReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsReaderClient : System.ServiceModel.ClientBase<EPSILab.Jupiter.Webservice.INewsReader>, EPSILab.Jupiter.Webservice.INewsReader {
        
        public NewsReaderClient() {
        }
        
        public NewsReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.Jupiter.Webservice.News GetNews(int code) {
            return base.Channel.GetNews(code);
        }
        
        public EPSILab.Jupiter.Webservice.News[] GetListNews() {
            return base.Channel.GetListNews();
        }
        
        public EPSILab.Jupiter.Webservice.News[] GetListNewsLimited(int indexFirstElement, int numberOfResults) {
            return base.Channel.GetListNewsLimited(indexFirstElement, numberOfResults);
        }
        
        public EPSILab.Jupiter.Webservice.News[] GetListNewsSorted(int indexFirstElement, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order) {
            return base.Channel.GetListNewsSorted(indexFirstElement, numberOfResults, order);
        }
        
        public int GetNewsLastInsertedId() {
            return base.Channel.GetNewsLastInsertedId();
        }
        
        public EPSILab.Jupiter.Webservice.News[] SearchNews(string keywords) {
            return base.Channel.SearchNews(keywords);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservice.IProjetReader")]
    public interface IProjetReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjetReader/GetProjet", ReplyAction="http://tempuri.org/IProjetReader/GetProjetResponse")]
        EPSILab.Jupiter.Webservice.Projet GetProjet(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjetReader/GetProjets", ReplyAction="http://tempuri.org/IProjetReader/GetProjetsResponse")]
        EPSILab.Jupiter.Webservice.Projet[] GetProjets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjetReader/GetProjetsLimited", ReplyAction="http://tempuri.org/IProjetReader/GetProjetsLimitedResponse")]
        EPSILab.Jupiter.Webservice.Projet[] GetProjetsLimited(int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjetReader/GetProjetsSorted", ReplyAction="http://tempuri.org/IProjetReader/GetProjetsSortedResponse")]
        EPSILab.Jupiter.Webservice.Projet[] GetProjetsSorted(int indexFirstElement, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjetReader/GetProjetsByVille", ReplyAction="http://tempuri.org/IProjetReader/GetProjetsByVilleResponse")]
        EPSILab.Jupiter.Webservice.Projet[] GetProjetsByVille(EPSILab.Jupiter.Webservice.Ville filter, int indexFirstElement, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjetReader/GetProjetLastInsertedId", ReplyAction="http://tempuri.org/IProjetReader/GetProjetLastInsertedIdResponse")]
        int GetProjetLastInsertedId();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjetReaderChannel : EPSILab.Jupiter.Webservice.IProjetReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjetReaderClient : System.ServiceModel.ClientBase<EPSILab.Jupiter.Webservice.IProjetReader>, EPSILab.Jupiter.Webservice.IProjetReader {
        
        public ProjetReaderClient() {
        }
        
        public ProjetReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjetReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjetReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjetReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.Jupiter.Webservice.Projet GetProjet(int code) {
            return base.Channel.GetProjet(code);
        }
        
        public EPSILab.Jupiter.Webservice.Projet[] GetProjets() {
            return base.Channel.GetProjets();
        }
        
        public EPSILab.Jupiter.Webservice.Projet[] GetProjetsLimited(int indexFirstElement, int numberOfResults) {
            return base.Channel.GetProjetsLimited(indexFirstElement, numberOfResults);
        }
        
        public EPSILab.Jupiter.Webservice.Projet[] GetProjetsSorted(int indexFirstElement, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order) {
            return base.Channel.GetProjetsSorted(indexFirstElement, numberOfResults, order);
        }
        
        public EPSILab.Jupiter.Webservice.Projet[] GetProjetsByVille(EPSILab.Jupiter.Webservice.Ville filter, int indexFirstElement, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order) {
            return base.Channel.GetProjetsByVille(filter, indexFirstElement, numberOfResults, order);
        }
        
        public int GetProjetLastInsertedId() {
            return base.Channel.GetProjetLastInsertedId();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservice.IPubliciteReader")]
    public interface IPubliciteReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPubliciteReader/GetPublicite", ReplyAction="http://tempuri.org/IPubliciteReader/GetPubliciteResponse")]
        EPSILab.Jupiter.Webservice.Publicite GetPublicite(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPubliciteReader/GetPublicites", ReplyAction="http://tempuri.org/IPubliciteReader/GetPublicitesResponse")]
        EPSILab.Jupiter.Webservice.Publicite[] GetPublicites();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPubliciteReaderChannel : EPSILab.Jupiter.Webservice.IPubliciteReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PubliciteReaderClient : System.ServiceModel.ClientBase<EPSILab.Jupiter.Webservice.IPubliciteReader>, EPSILab.Jupiter.Webservice.IPubliciteReader {
        
        public PubliciteReaderClient() {
        }
        
        public PubliciteReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PubliciteReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PubliciteReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PubliciteReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.Jupiter.Webservice.Publicite GetPublicite(int code) {
            return base.Channel.GetPublicite(code);
        }
        
        public EPSILab.Jupiter.Webservice.Publicite[] GetPublicites() {
            return base.Channel.GetPublicites();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservice.IRoleReader")]
    public interface IRoleReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleReader/GetRole", ReplyAction="http://tempuri.org/IRoleReader/GetRoleResponse")]
        EPSILab.Jupiter.Webservice.Role GetRole(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleReader/GetRoles", ReplyAction="http://tempuri.org/IRoleReader/GetRolesResponse")]
        EPSILab.Jupiter.Webservice.Role[] GetRoles();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoleReaderChannel : EPSILab.Jupiter.Webservice.IRoleReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoleReaderClient : System.ServiceModel.ClientBase<EPSILab.Jupiter.Webservice.IRoleReader>, EPSILab.Jupiter.Webservice.IRoleReader {
        
        public RoleReaderClient() {
        }
        
        public RoleReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoleReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.Jupiter.Webservice.Role GetRole(int code) {
            return base.Channel.GetRole(code);
        }
        
        public EPSILab.Jupiter.Webservice.Role[] GetRoles() {
            return base.Channel.GetRoles();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservice.ISalonReader")]
    public interface ISalonReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalonReader/GetSalon", ReplyAction="http://tempuri.org/ISalonReader/GetSalonResponse")]
        EPSILab.Jupiter.Webservice.Salon GetSalon(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalonReader/GetSalons", ReplyAction="http://tempuri.org/ISalonReader/GetSalonsResponse")]
        EPSILab.Jupiter.Webservice.Salon[] GetSalons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalonReader/GetSalonsLimited", ReplyAction="http://tempuri.org/ISalonReader/GetSalonsLimitedResponse")]
        EPSILab.Jupiter.Webservice.Salon[] GetSalonsLimited(int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalonReader/GetSalonsSorted", ReplyAction="http://tempuri.org/ISalonReader/GetSalonsSortedResponse")]
        EPSILab.Jupiter.Webservice.Salon[] GetSalonsSorted(int indexFirstElement, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalonReader/GetSalonLastInsertedId", ReplyAction="http://tempuri.org/ISalonReader/GetSalonLastInsertedIdResponse")]
        int GetSalonLastInsertedId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalonReader/SearchSalons", ReplyAction="http://tempuri.org/ISalonReader/SearchSalonsResponse")]
        EPSILab.Jupiter.Webservice.Salon[] SearchSalons(string keywords);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalonReaderChannel : EPSILab.Jupiter.Webservice.ISalonReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalonReaderClient : System.ServiceModel.ClientBase<EPSILab.Jupiter.Webservice.ISalonReader>, EPSILab.Jupiter.Webservice.ISalonReader {
        
        public SalonReaderClient() {
        }
        
        public SalonReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalonReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalonReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalonReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.Jupiter.Webservice.Salon GetSalon(int code) {
            return base.Channel.GetSalon(code);
        }
        
        public EPSILab.Jupiter.Webservice.Salon[] GetSalons() {
            return base.Channel.GetSalons();
        }
        
        public EPSILab.Jupiter.Webservice.Salon[] GetSalonsLimited(int indexFirstElement, int numberOfResults) {
            return base.Channel.GetSalonsLimited(indexFirstElement, numberOfResults);
        }
        
        public EPSILab.Jupiter.Webservice.Salon[] GetSalonsSorted(int indexFirstElement, int numberOfResults, EPSILab.Jupiter.Webservice.SortOrder order) {
            return base.Channel.GetSalonsSorted(indexFirstElement, numberOfResults, order);
        }
        
        public int GetSalonLastInsertedId() {
            return base.Channel.GetSalonLastInsertedId();
        }
        
        public EPSILab.Jupiter.Webservice.Salon[] SearchSalons(string keywords) {
            return base.Channel.SearchSalons(keywords);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservice.IVilleReader")]
    public interface IVilleReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilleReader/GetVille", ReplyAction="http://tempuri.org/IVilleReader/GetVilleResponse")]
        EPSILab.Jupiter.Webservice.Ville GetVille(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilleReader/GetVilles", ReplyAction="http://tempuri.org/IVilleReader/GetVillesResponse")]
        EPSILab.Jupiter.Webservice.Ville[] GetVilles();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVilleReaderChannel : EPSILab.Jupiter.Webservice.IVilleReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VilleReaderClient : System.ServiceModel.ClientBase<EPSILab.Jupiter.Webservice.IVilleReader>, EPSILab.Jupiter.Webservice.IVilleReader {
        
        public VilleReaderClient() {
        }
        
        public VilleReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VilleReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VilleReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VilleReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.Jupiter.Webservice.Ville GetVille(int code) {
            return base.Channel.GetVille(code);
        }
        
        public EPSILab.Jupiter.Webservice.Ville[] GetVilles() {
            return base.Channel.GetVilles();
        }
    }
}
