//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSILab.SolarSystem.Jupiter.ReadersService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Conference", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Conference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPSILab.SolarSystem.Jupiter.ReadersService.Campus CampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime End_DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Start_DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EPSILab.SolarSystem.Jupiter.ReadersService.Campus Campus {
            get {
                return this.CampusField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusField, value) != true)) {
                    this.CampusField = value;
                    this.RaisePropertyChanged("Campus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End_DateTime {
            get {
                return this.End_DateTimeField;
            }
            set {
                if ((this.End_DateTimeField.Equals(value) != true)) {
                    this.End_DateTimeField = value;
                    this.RaisePropertyChanged("End_DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublished {
            get {
                return this.IsPublishedField;
            }
            set {
                if ((this.IsPublishedField.Equals(value) != true)) {
                    this.IsPublishedField = value;
                    this.RaisePropertyChanged("IsPublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start_DateTime {
            get {
                return this.Start_DateTimeField;
            }
            set {
                if ((this.Start_DateTimeField.Equals(value) != true)) {
                    this.Start_DateTimeField = value;
                    this.RaisePropertyChanged("Start_DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Campus", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Campus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactEmail {
            get {
                return this.ContactEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactEmailField, value) != true)) {
                    this.ContactEmailField = value;
                    this.RaisePropertyChanged("ContactEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Link", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Link : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Order {
            get {
                return this.OrderField;
            }
            set {
                if ((this.OrderField.Equals(value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Member : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPSILab.SolarSystem.Jupiter.ReadersService.Campus CampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EPSIEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GitHubUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkedInUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonalEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PresentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPSILab.SolarSystem.Jupiter.ReadersService.Promotion PromotionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPSILab.SolarSystem.Jupiter.ReadersService.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TwitterUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViadeoUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EPSILab.SolarSystem.Jupiter.ReadersService.Campus Campus {
            get {
                return this.CampusField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusField, value) != true)) {
                    this.CampusField = value;
                    this.RaisePropertyChanged("Campus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityFrom {
            get {
                return this.CityFromField;
            }
            set {
                if ((object.ReferenceEquals(this.CityFromField, value) != true)) {
                    this.CityFromField = value;
                    this.RaisePropertyChanged("CityFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EPSIEmail {
            get {
                return this.EPSIEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EPSIEmailField, value) != true)) {
                    this.EPSIEmailField = value;
                    this.RaisePropertyChanged("EPSIEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookUrl {
            get {
                return this.FacebookUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookUrlField, value) != true)) {
                    this.FacebookUrlField = value;
                    this.RaisePropertyChanged("FacebookUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GitHubUrl {
            get {
                return this.GitHubUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.GitHubUrlField, value) != true)) {
                    this.GitHubUrlField = value;
                    this.RaisePropertyChanged("GitHubUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkedInUrl {
            get {
                return this.LinkedInUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkedInUrlField, value) != true)) {
                    this.LinkedInUrlField = value;
                    this.RaisePropertyChanged("LinkedInUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalEmail {
            get {
                return this.PersonalEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalEmailField, value) != true)) {
                    this.PersonalEmailField = value;
                    this.RaisePropertyChanged("PersonalEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Presentation {
            get {
                return this.PresentationField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentationField, value) != true)) {
                    this.PresentationField = value;
                    this.RaisePropertyChanged("Presentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EPSILab.SolarSystem.Jupiter.ReadersService.Promotion Promotion {
            get {
                return this.PromotionField;
            }
            set {
                if ((object.ReferenceEquals(this.PromotionField, value) != true)) {
                    this.PromotionField = value;
                    this.RaisePropertyChanged("Promotion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EPSILab.SolarSystem.Jupiter.ReadersService.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TwitterUrl {
            get {
                return this.TwitterUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.TwitterUrlField, value) != true)) {
                    this.TwitterUrlField = value;
                    this.RaisePropertyChanged("TwitterUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViadeoUrl {
            get {
                return this.ViadeoUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ViadeoUrlField, value) != true)) {
                    this.ViadeoUrlField = value;
                    this.RaisePropertyChanged("ViadeoUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Promotion", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Promotion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GraduationYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StillPresentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GraduationYear {
            get {
                return this.GraduationYearField;
            }
            set {
                if ((this.GraduationYearField.Equals(value) != true)) {
                    this.GraduationYearField = value;
                    this.RaisePropertyChanged("GraduationYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StillPresent {
            get {
                return this.StillPresentField;
            }
            set {
                if ((this.StillPresentField.Equals(value) != true)) {
                    this.StillPresentField = value;
                    this.RaisePropertyChanged("StillPresent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    public enum Role : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberActive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bureau = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="News", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class News : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPSILab.SolarSystem.Jupiter.ReadersService.Member MemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublished {
            get {
                return this.IsPublishedField;
            }
            set {
                if ((this.IsPublishedField.Equals(value) != true)) {
                    this.IsPublishedField = value;
                    this.RaisePropertyChanged("IsPublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keywords {
            get {
                return this.KeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordsField, value) != true)) {
                    this.KeywordsField = value;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EPSILab.SolarSystem.Jupiter.ReadersService.Member Member {
            get {
                return this.MemberField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberField, value) != true)) {
                    this.MemberField = value;
                    this.RaisePropertyChanged("Member");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortText {
            get {
                return this.ShortTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortTextField, value) != true)) {
                    this.ShortTextField = value;
                    this.RaisePropertyChanged("ShortText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EPSILab.SolarSystem.Jupiter.ReadersService.Campus CampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProgressionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EPSILab.SolarSystem.Jupiter.ReadersService.Campus Campus {
            get {
                return this.CampusField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusField, value) != true)) {
                    this.CampusField = value;
                    this.RaisePropertyChanged("Campus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Progression {
            get {
                return this.ProgressionField;
            }
            set {
                if ((this.ProgressionField.Equals(value) != true)) {
                    this.ProgressionField = value;
                    this.RaisePropertyChanged("Progression");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Slide", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Slide : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PresentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublished {
            get {
                return this.IsPublishedField;
            }
            set {
                if ((this.IsPublishedField.Equals(value) != true)) {
                    this.IsPublishedField = value;
                    this.RaisePropertyChanged("IsPublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Presentation {
            get {
                return this.PresentationField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentationField, value) != true)) {
                    this.PresentationField = value;
                    this.RaisePropertyChanged("Presentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Show", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Show : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime End_DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Start_DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End_DateTime {
            get {
                return this.End_DateTimeField;
            }
            set {
                if ((this.End_DateTimeField.Equals(value) != true)) {
                    this.End_DateTimeField = value;
                    this.RaisePropertyChanged("End_DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublished {
            get {
                return this.IsPublishedField;
            }
            set {
                if ((this.IsPublishedField.Equals(value) != true)) {
                    this.IsPublishedField = value;
                    this.RaisePropertyChanged("IsPublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start_DateTime {
            get {
                return this.Start_DateTimeField;
            }
            set {
                if ((this.Start_DateTimeField.Equals(value) != true)) {
                    this.Start_DateTimeField = value;
                    this.RaisePropertyChanged("Start_DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReadersService.IConferenceReader")]
    public interface IConferenceReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/GetConference", ReplyAction="http://tempuri.org/IConferenceReader/GetConferenceResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Conference GetConference(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/GetConferences", ReplyAction="http://tempuri.org/IConferenceReader/GetConferencesResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Conference[] GetConferences();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/GetConferencesLimited", ReplyAction="http://tempuri.org/IConferenceReader/GetConferencesLimitedResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Conference[] GetConferencesLimited(int indexFirstResult, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/GetConferencesByCampus", ReplyAction="http://tempuri.org/IConferenceReader/GetConferencesByCampusResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Conference[] GetConferencesByCampus(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/GetConferencesByCampusLimited", ReplyAction="http://tempuri.org/IConferenceReader/GetConferencesByCampusLimitedResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Conference[] GetConferencesByCampusLimited(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus, int indexFirstResult, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/GetConferenceLastInsertedId", ReplyAction="http://tempuri.org/IConferenceReader/GetConferenceLastInsertedIdResponse")]
        int GetConferenceLastInsertedId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceReader/SearchConferences", ReplyAction="http://tempuri.org/IConferenceReader/SearchConferencesResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Conference[] SearchConferences(string keywords);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConferenceReaderChannel : EPSILab.SolarSystem.Jupiter.ReadersService.IConferenceReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConferenceReaderClient : System.ServiceModel.ClientBase<EPSILab.SolarSystem.Jupiter.ReadersService.IConferenceReader>, EPSILab.SolarSystem.Jupiter.ReadersService.IConferenceReader {
        
        public ConferenceReaderClient() {
        }
        
        public ConferenceReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConferenceReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Conference GetConference(int code) {
            return base.Channel.GetConference(code);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Conference[] GetConferences() {
            return base.Channel.GetConferences();
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Conference[] GetConferencesLimited(int indexFirstResult, int numberOfResults) {
            return base.Channel.GetConferencesLimited(indexFirstResult, numberOfResults);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Conference[] GetConferencesByCampus(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus) {
            return base.Channel.GetConferencesByCampus(campus);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Conference[] GetConferencesByCampusLimited(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus, int indexFirstResult, int numberOfResults) {
            return base.Channel.GetConferencesByCampusLimited(campus, indexFirstResult, numberOfResults);
        }
        
        public int GetConferenceLastInsertedId() {
            return base.Channel.GetConferenceLastInsertedId();
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Conference[] SearchConferences(string keywords) {
            return base.Channel.SearchConferences(keywords);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReadersService.ILinkReader")]
    public interface ILinkReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILinkReader/GetLink", ReplyAction="http://tempuri.org/ILinkReader/GetLinkResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Link GetLink(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILinkReader/GetLinks", ReplyAction="http://tempuri.org/ILinkReader/GetLinksResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Link[] GetLinks();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILinkReaderChannel : EPSILab.SolarSystem.Jupiter.ReadersService.ILinkReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LinkReaderClient : System.ServiceModel.ClientBase<EPSILab.SolarSystem.Jupiter.ReadersService.ILinkReader>, EPSILab.SolarSystem.Jupiter.ReadersService.ILinkReader {
        
        public LinkReaderClient() {
        }
        
        public LinkReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LinkReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Link GetLink(int code) {
            return base.Channel.GetLink(code);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Link[] GetLinks() {
            return base.Channel.GetLinks();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReadersService.IMemberReader")]
    public interface IMemberReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberReader/GetMember", ReplyAction="http://tempuri.org/IMemberReader/GetMemberResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Member GetMember(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberReader/GetMembers", ReplyAction="http://tempuri.org/IMemberReader/GetMembersResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Member[] GetMembers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberReader/GetMembersByCampus", ReplyAction="http://tempuri.org/IMemberReader/GetMembersByCampusResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Member[] GetMembersByCampus(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberReader/GetMembersBureau", ReplyAction="http://tempuri.org/IMemberReader/GetMembersBureauResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Member[] GetMembersBureau();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberReader/GetMembersBureauByCampus", ReplyAction="http://tempuri.org/IMemberReader/GetMembersBureauByCampusResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Member[] GetMembersBureauByCampus(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberReader/GetMembersAlumnis", ReplyAction="http://tempuri.org/IMemberReader/GetMembersAlumnisResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Member[] GetMembersAlumnis(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberReader/GetMemberLastInsertedId", ReplyAction="http://tempuri.org/IMemberReader/GetMemberLastInsertedIdResponse")]
        int GetMemberLastInsertedId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberReader/SearchMembers", ReplyAction="http://tempuri.org/IMemberReader/SearchMembersResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Member[] SearchMembers(string keywords);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemberReaderChannel : EPSILab.SolarSystem.Jupiter.ReadersService.IMemberReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberReaderClient : System.ServiceModel.ClientBase<EPSILab.SolarSystem.Jupiter.ReadersService.IMemberReader>, EPSILab.SolarSystem.Jupiter.ReadersService.IMemberReader {
        
        public MemberReaderClient() {
        }
        
        public MemberReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Member GetMember(int code) {
            return base.Channel.GetMember(code);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Member[] GetMembers() {
            return base.Channel.GetMembers();
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Member[] GetMembersByCampus(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus) {
            return base.Channel.GetMembersByCampus(campus);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Member[] GetMembersBureau() {
            return base.Channel.GetMembersBureau();
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Member[] GetMembersBureauByCampus(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus) {
            return base.Channel.GetMembersBureauByCampus(campus);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Member[] GetMembersAlumnis(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus) {
            return base.Channel.GetMembersAlumnis(campus);
        }
        
        public int GetMemberLastInsertedId() {
            return base.Channel.GetMemberLastInsertedId();
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Member[] SearchMembers(string keywords) {
            return base.Channel.SearchMembers(keywords);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReadersService.INewsReader")]
    public interface INewsReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsReader/GetNews", ReplyAction="http://tempuri.org/INewsReader/GetNewsResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.News GetNews(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsReader/GetListNews", ReplyAction="http://tempuri.org/INewsReader/GetListNewsResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.News[] GetListNews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsReader/GetListNewsLimited", ReplyAction="http://tempuri.org/INewsReader/GetListNewsLimitedResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.News[] GetListNewsLimited(int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsReader/GetNewsLastInsertedId", ReplyAction="http://tempuri.org/INewsReader/GetNewsLastInsertedIdResponse")]
        int GetNewsLastInsertedId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsReader/SearchNews", ReplyAction="http://tempuri.org/INewsReader/SearchNewsResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.News[] SearchNews(string keywords);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsReaderChannel : EPSILab.SolarSystem.Jupiter.ReadersService.INewsReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsReaderClient : System.ServiceModel.ClientBase<EPSILab.SolarSystem.Jupiter.ReadersService.INewsReader>, EPSILab.SolarSystem.Jupiter.ReadersService.INewsReader {
        
        public NewsReaderClient() {
        }
        
        public NewsReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.News GetNews(int code) {
            return base.Channel.GetNews(code);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.News[] GetListNews() {
            return base.Channel.GetListNews();
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.News[] GetListNewsLimited(int indexFirstElement, int numberOfResults) {
            return base.Channel.GetListNewsLimited(indexFirstElement, numberOfResults);
        }
        
        public int GetNewsLastInsertedId() {
            return base.Channel.GetNewsLastInsertedId();
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.News[] SearchNews(string keywords) {
            return base.Channel.SearchNews(keywords);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReadersService.IProjectReader")]
    public interface IProjectReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectReader/GetProject", ReplyAction="http://tempuri.org/IProjectReader/GetProjectResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Project GetProject(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectReader/GetProjects", ReplyAction="http://tempuri.org/IProjectReader/GetProjectsResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Project[] GetProjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectReader/GetProjectsLimited", ReplyAction="http://tempuri.org/IProjectReader/GetProjectsLimitedResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Project[] GetProjectsLimited(int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectReader/GetProjectsByCampus", ReplyAction="http://tempuri.org/IProjectReader/GetProjectsByCampusResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Project[] GetProjectsByCampus(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectReader/GetProjectsByCampusLimited", ReplyAction="http://tempuri.org/IProjectReader/GetProjectsByCampusLimitedResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Project[] GetProjectsByCampusLimited(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus, int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectReader/GetProjectLastInsertedId", ReplyAction="http://tempuri.org/IProjectReader/GetProjectLastInsertedIdResponse")]
        int GetProjectLastInsertedId();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectReaderChannel : EPSILab.SolarSystem.Jupiter.ReadersService.IProjectReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectReaderClient : System.ServiceModel.ClientBase<EPSILab.SolarSystem.Jupiter.ReadersService.IProjectReader>, EPSILab.SolarSystem.Jupiter.ReadersService.IProjectReader {
        
        public ProjectReaderClient() {
        }
        
        public ProjectReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Project GetProject(int code) {
            return base.Channel.GetProject(code);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Project[] GetProjects() {
            return base.Channel.GetProjects();
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Project[] GetProjectsLimited(int indexFirstElement, int numberOfResults) {
            return base.Channel.GetProjectsLimited(indexFirstElement, numberOfResults);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Project[] GetProjectsByCampus(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus) {
            return base.Channel.GetProjectsByCampus(campus);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Project[] GetProjectsByCampusLimited(EPSILab.SolarSystem.Jupiter.ReadersService.Campus campus, int indexFirstElement, int numberOfResults) {
            return base.Channel.GetProjectsByCampusLimited(campus, indexFirstElement, numberOfResults);
        }
        
        public int GetProjectLastInsertedId() {
            return base.Channel.GetProjectLastInsertedId();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReadersService.ISlideReader")]
    public interface ISlideReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideReader/GetSlide", ReplyAction="http://tempuri.org/ISlideReader/GetSlideResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Slide GetSlide(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideReader/GetSlides", ReplyAction="http://tempuri.org/ISlideReader/GetSlidesResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Slide[] GetSlides();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISlideReaderChannel : EPSILab.SolarSystem.Jupiter.ReadersService.ISlideReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SlideReaderClient : System.ServiceModel.ClientBase<EPSILab.SolarSystem.Jupiter.ReadersService.ISlideReader>, EPSILab.SolarSystem.Jupiter.ReadersService.ISlideReader {
        
        public SlideReaderClient() {
        }
        
        public SlideReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SlideReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SlideReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SlideReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Slide GetSlide(int code) {
            return base.Channel.GetSlide(code);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Slide[] GetSlides() {
            return base.Channel.GetSlides();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReadersService.IShowReader")]
    public interface IShowReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowReader/GetShow", ReplyAction="http://tempuri.org/IShowReader/GetShowResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Show GetShow(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowReader/GetShows", ReplyAction="http://tempuri.org/IShowReader/GetShowsResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Show[] GetShows();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowReader/GetShowsLimited", ReplyAction="http://tempuri.org/IShowReader/GetShowsLimitedResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Show[] GetShowsLimited(int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowReader/GetShowLastInsertedId", ReplyAction="http://tempuri.org/IShowReader/GetShowLastInsertedIdResponse")]
        int GetShowLastInsertedId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowReader/SearchShows", ReplyAction="http://tempuri.org/IShowReader/SearchShowsResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Show[] SearchShows(string keywords);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShowReaderChannel : EPSILab.SolarSystem.Jupiter.ReadersService.IShowReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShowReaderClient : System.ServiceModel.ClientBase<EPSILab.SolarSystem.Jupiter.ReadersService.IShowReader>, EPSILab.SolarSystem.Jupiter.ReadersService.IShowReader {
        
        public ShowReaderClient() {
        }
        
        public ShowReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShowReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShowReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShowReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Show GetShow(int code) {
            return base.Channel.GetShow(code);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Show[] GetShows() {
            return base.Channel.GetShows();
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Show[] GetShowsLimited(int indexFirstElement, int numberOfResults) {
            return base.Channel.GetShowsLimited(indexFirstElement, numberOfResults);
        }
        
        public int GetShowLastInsertedId() {
            return base.Channel.GetShowLastInsertedId();
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Show[] SearchShows(string keywords) {
            return base.Channel.SearchShows(keywords);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReadersService.ICampusReader")]
    public interface ICampusReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampusReader/GetCampus", ReplyAction="http://tempuri.org/ICampusReader/GetCampusResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Campus GetCampus(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampusReader/GetCampuses", ReplyAction="http://tempuri.org/ICampusReader/GetCampusesResponse")]
        EPSILab.SolarSystem.Jupiter.ReadersService.Campus[] GetCampuses();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICampusReaderChannel : EPSILab.SolarSystem.Jupiter.ReadersService.ICampusReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CampusReaderClient : System.ServiceModel.ClientBase<EPSILab.SolarSystem.Jupiter.ReadersService.ICampusReader>, EPSILab.SolarSystem.Jupiter.ReadersService.ICampusReader {
        
        public CampusReaderClient() {
        }
        
        public CampusReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CampusReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampusReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampusReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Campus GetCampus(int code) {
            return base.Channel.GetCampus(code);
        }
        
        public EPSILab.SolarSystem.Jupiter.ReadersService.Campus[] GetCampuses() {
            return base.Channel.GetCampuses();
        }
    }
}
